@call ..\..\run_test.bat test027 ..\src\marty_utext\symbols_map.dat

@rem --no-ext  Remove file extention from autogenerated C-lang var name.
@rem --bin     Input is binary.
@rem --array   Generate output as byte array.
@rem --header  Generate header file (.h) instead of .c.
@rem --static  Generate static data.

2c --no-ext --bin --array --static ..\marty_utext\symbols_map.dat
